### ISSUE TITLE
GUI does not use auto-sizing (enough)

### ISSUE THREAD

**Issue by michaliskambi** [newpascal/fpcupdeluxe#12]
The forms of fpcupdeluxe do not use auto-sizing enough.

See the attached images how the forms look like on my Linux (Debian with MATE desktop, with larger fonts configured in MATE). As you can see, some text is too large for it's containing container (like a button or groupbox), and as a result it is partially cut off.

The window with "advanced options" is most hurt by this problem, but you can see some problems on all 3 screenshots.

To solve this, more controls should have AutoSize = true (all buttons, group boxes). And the controls should be anchored to their siblings (not have absolute positions). I could probably hack and submit at least a partial solution, if you're OK with this:)

![fpcupdeluxe_no_autosizing_1](https://cloud.githubusercontent.com/assets/1076978/24731411/2773e670-1a6a-11e7-8c8e-a2650feebcc4.png)
![fpcupdeluxe_no_autosizing_2](https://cloud.githubusercontent.com/assets/1076978/24731412/27918d10-1a6a-11e7-85fe-4f70df5761d3.png)
![fpcupdeluxe_no_autosizing_3](https://cloud.githubusercontent.com/assets/1076978/24731413/279ea0ae-1a6a-11e7-95dc-af2b1089995f.png)

**Comment by LongDirtyAnimAlf** [comment]
Partly solved. Unfortunately, hard to solve for all GUI elements.
Will be a work-in-progress.

**Comment by michaliskambi** [comment]
I'm afraid that the issue still remains, many controls are still incorrect on my system. I attach the latest screenshots. I know that you wrote that the issue is only partially solved, but comparing the screenshots -- I'm afraid that I don't see much improvements.

If it's OK with you, I would ask to reopen this request, until it is resolved more completely. I know that it's difficult to solve 100%, but I can see some ways how to resolve it 90% :)

And I emphasize that I'm very eager to handle this myself, if it's OK with you!

Feel free to reopen this issue and assign me to it. I would happily submit a pull request with everything ready and tested on my system (and others too, I can test on Windows and Mac as well). I'm asking before making a pull request, because I suspect that the changes to the *.lfm files will be substantial, so to make it easy to merge them -- you should be ready, and avoid changing *.lfm files for a short time.

I hope that I'm not causing too much hassle -- I just want the GUI to look as-perfect-as-possible on my system, and I'm prepared to make the necessary changes myself :) Please let me know if that's OK:)

![fpcupdeluxe_1](https://cloud.githubusercontent.com/assets/1076978/25407353/53479de6-2a0a-11e7-8bde-38cdee1ee1f4.png)
![fpcupdeluxe_2](https://cloud.githubusercontent.com/assets/1076978/25407355/537ab870-2a0a-11e7-97f2-9e8521de52a1.png)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your feedback !
And yes, is see there are still GUI issues.

My POV:
Fpcupdeluxe is a single us, one shot app, used to install FPC and Lazarus.
As such, the GUI is only functional, but need not to be perfect.

My new POV:
I appreciate your (GUI) efforts very much.
Feel free to make the necessary changes.
But remember: keep the GUI as simple as possible.
Fpcupdeluxe needs to remain self-explanatory by its GUI. Fire-up, use and forget.
And most users only use the main GUI.
Again, thanks for your help.

**Comment by michaliskambi** [comment]
Great! I'll try to submit something useful within the next few days:)

I absolutely agree with you about the need to keep a simple GUI. As part of this issue, I don't want to change the GUI at all -- I only want to make it use auto-sizing more. The change will be almost impossible to notice, if the GUI already fits nicely your theme font size.

**Comment by LongDirtyAnimAlf** [comment]
GUI has been improved a lot in the meantime.
Many issues solved.
Closing for now.

**Comment by michaliskambi** [comment]
Absolutely, it's indeed much better now. I'm attaching the screenshots from the latest fpcupdeluxe on my system -- it's not perfect (some labels overlap and some buttons are smaller than the text inside), but it's readable, both the main window and the "Advanced settings". Thanks for your work!

And I'm sorry for now providing patches -- I promised to submit a pull request addressing this, but I never found the time to do it.

![fpcupdeluxe1](https://user-images.githubusercontent.com/1076978/31737145-e2371a38-b446-11e7-930a-821569e4e8be.png)
![fpcupdeluxe2](https://user-images.githubusercontent.com/1076978/31737146-e26fd558-b446-11e7-839a-e0028d9ff6ce.png)

**Comment by LongDirtyAnimAlf** [comment]
I will try to solve (some of) the above issues (as shown in the screenshots) in a next release.
It is hard to get the GUI ok on all systems.
