### ISSUE TITLE
Possibiilty to get "stable" package versions

### ISSUE THREAD

**Issue by michaliskambi** [newpascal/fpcupdeluxe#14]
(This is a (rather low-priority) feature request :)

For Castle Game Engine, fpcupdeluxe takes the code from SVN trunk (or GIT master, after resolving my pull request: https://github.com/newpascal/fpcupdeluxe/pull/11 ). This means that I can easily temporarily break Castle Game Engine in fpcupdeluxe by making a mistaken commit.

(I usually take pride in having a stable repository, and it's automatically tested by Jenkins... but accidents happen anyway. Especially with many OS/CPU/FPC/Lazarus combinations.)

And the way "ArchiveURL" is currently used doesn't help. Although my pull request https://github.com/newpascal/fpcupdeluxe/pull/11 adds an "ArchiveURL" with a stable zip to fpcup.ini for CGE, but the "ArchiveURL" is used only in case the GIT/SVN repository cannot be contacted.

What I would like is a button like *"Install STABLE versions of the selected modules"*, right next to the *"Install module(s) from list"* (which could be renamed to *"Install LATEST versions of the selected modules"*).

I see two possible ways to implement this:

- The "stable" version could require a new module settings in fpcup.ini: `StableGITUR`L, `StableSVNURL`, `StableArchiveURL` . This seems like the most flexible approach, and consistent with current design. For GIT, it would be useful to add `GITBranch` and `StableGITBranch`, in case the module uses two different branches within the same repository (e.g. "stable" and "master", or "master" and "unstable").

- An alternative way: the "stable" version could just use ArchiveURL (never SVN or GIT), and assuming that projects will update ArchiveURL to specify their latest stable zip/tar.gz. This makes some sense, as it also allows to put more things (like an offline documentation generated by PasDoc in case of CGE) inside the "stable" release zip. But it's probably not consistent with current ArchiveURL usage (right now, in fpcup.ini, most ArchiveURL point to GitHub "master.zip" file, so they are *not* used to provide a stable zip releases).

**Comment by LongDirtyAnimAlf** [comment]
I am closing this, due to the fact that Lazarus trunk has OPM.
Which makes the module-installer of fpcupdeluxe more or less obsolete.
