### ISSUE TITLE
How to use on FreeBSD

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#18]
Tried FreeBsd, cannot use Lazarus 1.6.4 there- installer has bug
Pls write Wiki about how to use app on FreeBsd, to install Laz trunk and FPC trunk in it

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by this commit:
https://github.com/newpascal/fpcupdeluxe/commit/18cd9be80d7331066606394f7bcebd21fc036c07

Will update wiki later !
