### ISSUE TITLE
Er on installing cross compiler Linux-arm

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#20]
Ubuntu x64
installed Laz+FPC
Now on pressing button for cross-compiler, i get errors.
Cannot download utils from web? I pressed "yes- download".

![bin-util--](https://cloud.githubusercontent.com/assets/4154978/25249126/79935ab6-2619-11e7-8ee9-a7ef84daeccf.png)

**Comment by LongDirtyAnimAlf** [comment]
The white windows is a (error) summary of the main (green) command output window.
So, fpcupdeluxe tried to build a cross-compiler, did not succeed, asked for permission to get the cross-utils, continued and succeeded.
The main (green) command output window is your friend !!
