### ISSUE TITLE
Menuitem About/Activate

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#22]
menu items does nothing.
Pls delete it in Main menu.

**Comment by LongDirtyAnimAlf** [comment]
Could you please elaborate on this one ?

**Comment by Alexey-T** [comment]
I click Ubuntu's title of window, and see menuuitem About
![mi-2](https://cloud.githubusercontent.com/assets/4154978/25399207/4a3b07be-29f7-11e7-9401-7e4dac439c2b.png)

**Comment by LongDirtyAnimAlf** [comment]
This is (very) strange, but I will look into it.

**Comment by LongDirtyAnimAlf** [comment]
I cannot reproduce this on any of my systems !
So, I will close due to unable to solve.
Sorry about this.
