### ISSUE TITLE
Desktop link dont start

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#28]
link: fpcup-Lazarus_fpcupdeluxe.desktop
don't start. Error

```
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Icon=/home/user/fpcupdeluxe/lazarus/images/icons/lazarus.ico
Exec=/home/user/fpcupdeluxe/lazarus/lazarus --pcp="/home/user/fpcupdeluxe/config_lazarus"
Name=Lazarus_fpcupdeluxe
Category=Application;IDE;Development;GUIDesigner;
Keywords=editor;Pascal;IDE;FreePascal;fpc;Design;Designer;
```

![untr](https://cloud.githubusercontent.com/assets/4154978/25554194/c2ca4db8-2ccf-11e7-9d23-730c3bdbc264.png)

**Comment by Alexey-T** [comment]
It has attrib -rwx------.

**Comment by Alexey-T** [comment]
After setting "allow execute" from ubuntu it works. (-rwx--x--x)

**Comment by LongDirtyAnimAlf** [comment]
Ok. Closing.

**Comment by Alexey-T** [comment]
Fpcup must set this attr, pls

**Comment by LongDirtyAnimAlf** [comment]
Done:
https://github.com/newpascal/fpcupdeluxe/commit/e3abf47e3a5f8a5ad3e4512a9fe76bb742a520f1

**Comment by Alexey-T** [comment]
Thanks.
