### ISSUE TITLE
Ubuntu 17.04 - thread support ?

### ISSUE THREAD

**Issue by sirhelly** [newpascal/fpcupdeluxe#32]
I successfully used fpcupdeluxe to install fpc 302 and lazarus 1.6.4.
But when i choose "bgrabitmap" and install module(s) from the application just closes.
I tried on the console and got:
```
./fpcupdeluxe-x86_64-linux 
This binary has no thread support compiled in.
Recompile the application with a thread-driver in the program uses clause before other units using thread.
WARNING: TButton.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
Runtime error 232 at $0000000000437B1D
```
This looks a bit like a missing cthreads unit or so ?

**Comment by LongDirtyAnimAlf** [comment]
You are right: this is a bug.
Has been fixed in the latest release (1.4.0a).
I have replaced all Linux binaries with new ones. Please re-download.
