### ISSUE TITLE
config dialog needs fix

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#41]
- checkboxes don't fit.
- 2 edits overlap and labels

Ubuntu

![lin 2](https://user-images.githubusercontent.com/4154978/31057828-a0fa83be-a6f1-11e7-9efc-7c69bede05e4.png)

**Comment by Alexey-T** [comment]
3 - pls delete  border around OK/cancel.

**Comment by LongDirtyAnimAlf** [comment]
Done.  But border around OK/cancel will stay for resizing.
