### ISSUE TITLE
How to build cross compilers in current lazarus installation?

### ISSUE THREAD

**Issue by cpicanco** [newpascal/fpcupdeluxe#43]
Hi, I have Lazarus 1.8RC4 and fpc 3.0.4 installed. I did not use fpcupdeluxe for these. How to build cross compilers using fpcupdeluxe this installation?

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe uses its own install.
As it is already difficult enough to handle all different os and cpu, so this feature will NOT be implemented.
Please use fpcupeluxe to make its own install. Followed by cross-compilers.
Thanks.
