### ISSUE TITLE
Target OS "Haiku"

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#44]
maybe add it - it's new good OS.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind testing ?
https://github.com/newpascal/fpcupdeluxe/releases/tag/v1.4.0t

**Comment by Alexey-T** [comment]
I tried but cannot test, copied this app to ISO file and used in OS.

1- App needs linQt5Pas, and of coz in Haiku format.
2- And Qt5 too. Haiku current build cannot install more software (software manager fails)

**Comment by LongDirtyAnimAlf** [comment]
Haiku is added. Will close due to lack of test results.
Re-open when results are available.
