### ISSUE TITLE
Can't build OSX cross compiler from debian.

### ISSUE THREAD

**Issue by cpicanco** [newpascal/fpcupdeluxe#45]
I am migrating the issue from this forum:
http://forum.lazarus.freepascal.org/index.php/topic,38596.0.html

```
make 'FPC=/home/rafael/fpcupdeluxe/fpcsrc/compiler/ppcrossx64' rtlclean rtl CYCLELEVEL=3
make -C /home/rafael/fpcupdeluxe/fpcsrc/rtl clean
make -C darwin clean
make -C /home/rafael/fpcupdeluxe/fpcsrc/rtl 'OPT=-vw-n-h-l-d-u-t-p-c-    ' all
make -C darwin all
/home/rafael/fpcupdeluxe/fpcsrc/compiler/ppcrossx64 -dNOMOUSE -Ur -dFPC_USE_LIBC -Tdarwin -XPx86_64-apple-darwin15- -Xr -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fi../bsd -Fi../bsd/x86_64 -Fi../darwin/x86_64 -FD/home/rafael/fpcupdeluxe/cross/bin/x86-darwin -FE. -FU/home/rafael/fpcupdeluxe/fpcsrc/rtl/units/x86_64-darwin -vw-n-h-l-d-u-t-p-c- -dx86_64 -dRELEASE -XPx86_64-apple-darwin15- -Xd -Fl/home/rafael/fpcupdeluxe/cross/lib/x86-darwin/MacOSX10.11.sdk/usr/lib -Fl/home/rafael/fpcupdeluxe/cross/lib/x86-darwin/MacOSX10.11.sdk/usr/lib/system -Us -Sg ../bsd/system.pp
/home/rafael/fpcupdeluxe/cross/bin/x86-darwin/x86_64-apple-darwin15-clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/rafael/fpcupdeluxe/cross/bin/x86-darwin/x86_64-apple-darwin15-clang)
system.pp(387) Error: Error while assembling exitcode 1
system.pp(387) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Makefile:2829: recipe for target 'system.ppu' failed
make[5]: *** [system.ppu] Error 1
Makefile:2505: recipe for target 'darwin_all' failed
make[4]: *** [darwin_all] Error 2
Makefile:4327: recipe for target 'rtl' failed
make[3]: ***
Error 2
Makefile:4229: recipe for target 'cycle' failed
make[2]: *** [cycle] Error 2
Makefile:2908: recipe for target 'compiler_cycle' failed
make[1]: *** [compiler_cycle] Error 2
Makefile:2940: recipe for target 'build-stamp.x86_64-darwin' failed
make: *** [build-stamp.x86_64-darwin] Error 2
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc make all for x86_64-darwin failed with an error code.


ERROR: Fpcupdeluxe fatal error !
Building cross-tools failed ... ??? ... aborting.
```

- [x] fpc trunk installed through fpcupdeluxe
- [x] clang installed by me (sudo apt-get install clang)
- [x] binutils and libs downloaded by fpcupdeluxe
- [x] binutils and libs extracted by fpcupdeluxe
- [ ] cross-compiler built :cry: 
- [ ] cross-compiler installed :cry:

**Comment by LongDirtyAnimAlf** [comment]
https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
https://askubuntu.com/questions/719028/version-glibcxx-3-4-21-not-found
https://stackoverflow.com/questions/19386651/how-to-fix-usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found

Please have a look at the above links.
If not helpful, please add more comments here.

**Comment by cpicanco** [comment]
Sorry, I am not an Ubuntu user. I am having a problem using fpcupdeluxe in debian. Those links are Ubuntu related problems or hacked related systems.

**Comment by LongDirtyAnimAlf** [comment]
I will see if I can build for Debian x86_64.
What Debian version are you on ?

**Comment by cpicanco** [comment]
I am using a distribution that is 100% on top of debian stable, in this case Debian 9. https://www.bunsenlabs.org/

**Comment by LongDirtyAnimAlf** [comment]
Alright.
I am going to (try to) build the tools on Debian9.

**Comment by LongDirtyAnimAlf** [comment]
I have added new tools for Debian Linux v9.2.1. Fresh install. Fresh build.
https://github.com/newpascal/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsDarwinx86-debian.zip
Please replace the originals tools with these tools and test.

**Comment by LongDirtyAnimAlf** [comment]
![debian](https://user-images.githubusercontent.com/10783972/31709586-ba323170-b3f2-11e7-8f6a-31d6f625d4e3.JPG)

**Comment by cpicanco** [comment]
I must say that I committed a terrible mistake. Sorry about that. My actual system was Jessy (Debian 8). After updating to Stretch (Debian 9), I was able to compile using the same binaries. I assumed (incorrectly) that Deuterium used 9 and Hydrogen used 8.

> Released on April 29, 2017. Read the announcement here. This is a refresh of the earlier Hydrogen release, which was also based on Debian Jessie.↩
