### ISSUE TITLE
Great tool but

### ISSUE THREAD

**Issue by limelect** [newpascal/fpcupdeluxe#46]
It has a lot of potential but for now it is not usable.
It seem that the program dose not wait for its down loads to finish and as
for that it it get an error and fails.
My first down load was the  openssl that i head to download
by hand. Then there was the fcp   git32.7z  it self that failed so i gave up.
 I wanted to have an Android +arm .
Further more the wiki dose not explain  well all the option since i head to guess.

**Comment by LongDirtyAnimAlf** [comment]
Yes, the wiki can use a lot more attention ! I will make some time for it.

Your problem is not that clear to me.
The install does not work for you due to download failures ?
And you want to install an android-arm cross-compiler ?

If you want my help, I need to know what goes wrong with your system.
So please copy and show the green-screen output in full verbosity mode.

**Comment by limelect** [comment]
FPCUPdeluxe V1.6.0a base fpcup036 (20171017) for i386-win32-win32

Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

Binutils/make dir:  C:\fpcupdeluxe\fpcbootstrap
Bootstrap dir:      C:\fpcupdeluxe\fpcbootstrap
FPC URL:               http://svn.freepascal.org/svn/fpc/tags/release_3_0_2
FPC options:           
FPC source directory:  C:\fpcupdeluxe\fpcsrc
FPC install directory: C:\fpcupdeluxe\fpc
Lazarus URL:        http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6_4
Lazarus options:    
Lazarus directory:  C:\fpcupdeluxe\lazarus
Please stand back and enjoy !

fpcupdeluxe: info: 22/10/2017 15:31:39: fpcup036 (20171017) started.
fpcupdeluxe: info: Windows major version: 6
fpcupdeluxe: info: Windows minor version: 1
fpcupdeluxe: info: Windows build number:  7601
fpcupdeluxe: info: FPCNativeInstaller (GetFile): GIT not found. Download it (may take time) from https://github.com/newpascal/fpcupdeluxe/releases/download/Git-2.13.2
fpcupdeluxe: info: FPCNativeInstaller (GetFile): GIT download ready: unpacking (may take time).
Executing: C:\fpcupdeluxe\fpcbootstrap\\7Zip\7za.exe "x" "-oC:\fpcupdeluxe\fpcbootstrap\git\" "C:\fpcupdeluxe\fpcbootstrap\git\git32.7z" (working dir: )

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\fpcupdeluxe\fpcbootstrap\git\git32.7z

Error: Can not open file as archive

Executing: 7z.exe "x" "-oC:\fpcupdeluxe\fpcbootstrap\git\" "C:\fpcupdeluxe\fpcbootstrap\git\git32.7z" (working dir: )
Executing: 7za.exe "x" "-oC:\fpcupdeluxe\fpcbootstrap\git\" "C:\fpcupdeluxe\fpcbootstrap\git\git32.7z" (working dir: )
fpcupdeluxe: info: C:\fpcupdeluxe\fpcbootstrap\git\bin\git.exe is not a valid git.exe application (git.exe result code was: -1)
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe' is not a working copy
fpcupdeluxe: info: Directory C:\fpcupdeluxe\fpcsrc is not an SVN repository (or a repository with the wrong remote URL).
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): Creating directory C:\fpcupdeluxe\fpcsrc for SVN checkout.
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): Running SVN checkout or update.
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "checkout" "--quiet" "--non-interactive" "--trust-server-cert" "-r" "HEAD" "http://svn.freepascal.org/svn/fpc/tags/release_3_0_2/" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: Repository moved permanently to 'https://svn.freepascal.org/svn/fpc/tags/release_3_0_2'; please relocate
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "checkout" "--quiet" "--non-interactive" "--trust-server-cert" "-r" "HEAD" "http://svn.freepascal.org/svn/fpc/tags/release_3_0_2/" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: Repository moved permanently to 'https://svn.freepascal.org/svn/fpc/tags/release_3_0_2'; please relocate
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "checkout" "--quiet" "--non-interactive" "--trust-server-cert" "-r" "HEAD" "http://svn.freepascal.org/svn/fpc/tags/release_3_0_2/" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: Repository moved permanently to 'https://svn.freepascal.org/svn/fpc/tags/release_3_0_2'; please relocate
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "cleanup" "--non-interactive" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy directory
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "update" "--quiet" "--non-interactive" "--trust-server-cert" "-r" "HEAD" "C:\fpcupdeluxe\fpcsrc" (working dir: )
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\Subversion Client\svn.exe "info" "C:\fpcupdeluxe\fpcsrc" (working dir: )
svn: 'C:\fpcupdeluxe\fpcsrc' is not a working copy
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at: failure
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No updates for FPC found.
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: ERROR: Tried to get FPC version from version.pas, but no version.pas found
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): We have a FPC source (@ C:\fpcupdeluxe\fpcsrc) with version: 0.0.0
fpcupdeluxe: ERROR: Tried to get required bootstrap compiler version from Makefile.fpc, but no Makefile.fpc found
fpcupdeluxe: ERROR: Tried to get required bootstrap compiler version from Makefile.fpc, but no Makefile.fpc found
fpcupdeluxe: ERROR: Tried to get FPC version from version.pas, but no version.pas found
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModule: FPC): Could not determine required bootstrap compiler version. Should not happen. Aborting.
fpcupdeluxe: ERROR: Sequencer (fpc): Failure running fpcupdeluxe: error executing sequence fpc; instr: SMbuildmodule; line: 6, param: FPC
fpcupdeluxe: ERROR: Sequencer (DefaultWin32): Failure running fpcupdeluxe: error executing sequence DefaultWin32; instr: SMdo; line: 3, param: fpc


ERROR: Fpcupdeluxe fatal error !

**Comment by limelect** [comment]
![screenshot - 07_10_2017 21_58_32](https://user-images.githubusercontent.com/4199131/31861953-7fbd2d5c-b73e-11e7-990a-8cc42e0f17fc.png)

Last time https://github.com/newpascal/fpcupdeluxe/releases/download/Git-2.13.2 did not work
As i said openssl had at first to download manually. never passed this point.

**Comment by limelect** [comment]
Last question is it possible to install on a USB?

**Comment by traumschule** [comment]
yes, you can change the paths in settings.ini. The easiest may be to make ~/development or c:\development a link to a folder on the USB drive.

**Comment by LongDirtyAnimAlf** [comment]
Will close for now.
Please re-open in case of renewed problems !
