### ISSUE TITLE
Building Darwin cross-compilers from Lubuntu 17.10 fails

### ISSUE THREAD

**Issue by m-audio91** [newpascal/fpcupdeluxe#47]
Hi,  
I encountered an error after switched my dev machine to a fresh os.
my error message is inside your collected data at   
http://54.194.211.233:8880/root/getinfohtml?ShowErrors=yes  

> 1.6.0b  
x86_64-linux  
Ubuntu 4.13.0-16-generic  
gtk2  
Iran  
2017-10-22T21:44:28  
Install cross  
trunk  
trunk  
darwin-x86_64  
{"Only":"FPCCleanOnly,FPCBuildOnly"}  
Building compiler for darwin-x86_64. fpcupdeluxe: info: TAny_darwin-x86_64: found correct binary utilities in directory /home/vboxuser/devel/lazfpctrunkcross/cross/bin/x86-darwin fpcupdeluxe: info: TAny_darwin-x86_64: found correct library in directory /home/vboxuser/devel/lazfpctrunkcross/cross/lib/x86-darwin/MacOSX10.11.sdk/usr/lib system.pp(387) Error: Can't call the assembler, error 127 switching to external assembling Most likely, there is not enough RAM (swap) to finish this operation. Please add some swap-space (1GB) and re-run fpcupdeluxe. system.pp(387) Fatal: There were 2 errors compiling module, stopping system.pp(387) Error: Can't call the assembler, error 127 switching to external assembling Fatal: Compilation aborted system.pp(387) Fatal: There were 2 errors compiling module, stopping fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc make all for x86_64-darwin failed with an error code. fpcupdeluxe: ERROR: Sequencer (FPCBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCBuildOnly; instr: SMbuildmodule; line: 2, param: FPC fpcupdeluxe: ERROR: Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only; instr: SMdo; line: 2, param: FPCBuildOnly
  

building win32-i386 and linux-i386 cross-compilers went fine. but both darwini386 and darwinx86_64 fails with the same error message.  
the Lubuntu installation is fresh.  memory usage is 500MB of 2048MB at that point so it does not sounds like a swap-space issue?  
I don't know what this link says is related to my problem or not:  https://www.freepascal.org/faq.var#os2-as-failing  

what should I do?

**Comment by m-audio91** [comment]
you've recently released https://github.com/newpascal/fpcupdeluxe/tree/crosslibs_v1.1

can't it be related to my Issue? a mismatch between libs and bins?

**Comment by LongDirtyAnimAlf** [comment]
A lot of changes went into the latest releases, so you could be right.
Will look into this issue.

**Comment by LongDirtyAnimAlf** [comment]
It indeed seemed to be a library issue !
Library for Darwin has been updated.
Please remove the darwin-x86 folder from your cross-lib folder, and use fpcupdeluxe again !

**Comment by m-audio91** [comment]
Thanks,
Building Darwin i386 cross compiler = SUCCESS
Building Darwin x8664 cross compiler = SUCCESS
cross-compiling one project that used to cross-compile fine with 1.4.0s release, now returns error while linking:

> ld: framework not found AppKit
An error occured while linking

**Comment by LongDirtyAnimAlf** [comment]
Seen it also ... will solve !

**Comment by LongDirtyAnimAlf** [comment]
Please delete libs and try again !

**Comment by m-audio91** [comment]
SUCCESS!
Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for testing !
