### ISSUE TITLE
Setup dlg: not native btn height

### ISSUE THREAD

**Issue by Alexey-T** [newpascal/fpcupdeluxe#49]
For btns: List / Libraries / Tools / OK / Cancel
Pls make AutoSize=true and anchors.

bottom 4 btns maybe too.

![screenshot from 2017-11-03 12-46-36](https://user-images.githubusercontent.com/4154978/32367976-33ea37a2-c095-11e7-82d5-5a50f936867f.png)

**Comment by LongDirtyAnimAlf** [comment]
Please see latest release.
