### ISSUE TITLE
fpcupdeluxe halts without logging anything

### ISSUE THREAD

**Issue by leonardorame** [newpascal/fpcupdeluxe#5]
Hi, I just downloaded fpcupdeluxe on ~/fpcupdeluxe (XUbuntu 16.04 - x86_64), run it then click on Stable, it downloaded everything needed from SVN, then started compiling, but when compiling Lazarus the application closes (core dumped).

I don't know where it halted, because I don't have a log to take a look into. Is there a way to write the log to a file?.

Regards,
Leonardo.

**Comment by LongDirtyAnimAlf** [comment]
I would suggest to just run fpcupdeluxe again.
It will re-use all your sources.

Besides, I just did a clean install on my linux-mint of stable without any problems !
So, at the moment, I cannot reproduce your problem unfortunately.

**Comment by leonardorame** [comment]
Yea, I tried many times before writing..also tried installing FPC only and it finished without errors, but now, when I call "fpc" from command line it isn't found.

Also it looks fpcup doesn't creates the ~/.fpc.cfg file.

**Comment by LongDirtyAnimAlf** [comment]
Sure, it does not create ~/.fpc.cfg !
Fpcupdeluxe tries to isolate itself completely. No influence on existing install, no changes to path, no changes to system settings.
Due to this, you HAVE to start fpc (and Lazarus) with the supplied link (shortcut), that is made by fpcupdeluxe !!
Otherwise, things will not work !!

**Comment by leonardorame** [comment]
Mmm. No desktop shortcut here.

At least I've found when fpcupdeluxe halts, it halts when I try to compile Lazarus Stable, if I change it to Trunk it stops with this code:

```
fpcupdeluxe: info: Running SVN checkout or update.
Executing : /usr/bin/svn "info" "/home/gabriel/fpcupdeluxe/lazarusfpc/lazarus" (working dir: )
Ruta: /home/gabriel/fpcupdeluxe/lazarusfpc/lazarus
Working Copy Root Path: /home/gabriel/fpcupdeluxe/lazarusfpc/lazarus
URL: http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6_2
Relative URL: ^/tags/lazarus_1_6_2
Raíz del repositorio: http://svn.freepascal.org/svn/lazarus
UUID del repositorio: 4005530d-fff6-0310-9dd1-cebe43e6787f
Revisión: 53974
Tipo de nodo: directorio
Agendado: normal
Autor del último cambio: mattias
Revisión del último cambio: 53354
Fecha de último cambio: 2016-11-12 06:48:11 -0300 (sáb 12 de nov de 2016)

fpcupdeluxe: info: ERROR: repository URL in local directory and remote repository don't match.
fpcupdeluxe: info: Local directory: /home/gabriel/fpcupdeluxe/lazarusfpc/lazarus
fpcupdeluxe: info: Lazarus was at: failure
fpcupdeluxe: info: No updates for Lazarus found.
fpcupdeluxe: ERROR: Checking out/updating Lazarus sources failure
fpcupdeluxe: info: Error running fpcup. Technical details: error executing sequence lazarus; line: 3, param: lazarus
fpcupdeluxe: info: Error running fpcup. Technical details: error executing sequence Only; line: 1, param: lazarus


ERROR: Fpcupdeluxe failed.

```

**Comment by LongDirtyAnimAlf** [comment]
Lazarus-stable and Lazarus-trunk are different repo's.
As are fpc-stable and fpc-trunk.
The error says it all: repository URL in local directory and remote repository don't match.
You have to use separate install-directories for different versions of Lazarus and/or fpc.

My advice
use "lazstable" for stable.
use "laztrunk" for trunk.
use ....

About the desktop-shortcut.
This will only be created after successfull install of Lazarus. Which is not the case yet.

**Comment by leonardorame** [comment]
Thanks! finally compiled successfully by following your advice.

**Comment by LongDirtyAnimAlf** [comment]
Good !
Have fun !!
