### ISSUE TITLE
use git-svn with existing trunk folder

### ISSUE THREAD

**Issue by traumschule** [newpascal/fpcupdeluxe#57]
Hi! Thanks for this tools, the GUI looks powerful.

is it possible to use an existing repository, checked out with "git svn clone https://svn.freepascal.org/svn/fpc/trun"?

This is what I did:
```
git svn clone https://svn.freepascal.org/svn/fpc/trunk ~/src/fpc
git clone https://github.com/newpascal/fpcupdeluxe ~/src/fpcupdeluxe
cd ~/src/fpcupdeluxe
fpcupdeluxe(master)$ lazbuild fpcupdeluxe.lpi
fpcupdeluxe(master)$ ./bin/fpcup-i386-linux --fpcdir=~/src/fpc --keeplocalchanges --svnexe='/usr/bin/git svn' --verbose
```
It seems that the arguments are ignored. When I set the path in the GUI and click on the  button "FPC only" it tries to checkout the repository to `~/src/fpc/fpcsrc`.

**Comment by LongDirtyAnimAlf** [comment]
At this moment, this is not possible.
But I will look into adding this as a feature.
