### ISSUE TITLE
Installation fails while installing Oracle because of Windows "common.dll".

### ISSUE THREAD

**Issue by bottleneck58** [newpascal/fpcupdeluxe#575]
......
External command "C:/laz4android/fpcsrc/compiler/ppc386.exe -Twin32 -FUoracle\units\i386-win32\ -FuC:\laz4android\fpcsrc\rtl\units\i386-win32\ -Fuoracle\src -Fioracle\src -Ur -Xs -O2 -n -vw-n-h-l-d-u-t-p-c- -di386 -dRELEASE -XX -CX -Sc -viq oracle\BuildUnit_oracle.pp" failed with exit code 1. Console output:
Target OS: Win32 for i386
Compiling oracle\BuildUnit_oracle.pp
Compiling .\oracle\src\oratypes.pp
Compiling .\oracle\src\ocidyn.pp
Compiling .\oracle\src\oci.pp
Compiling .\oracle\src\oraoci.pp
oraoci.pp(1437) Error: Invalid DLL C:\Windows\system32\common.dll, invalid header size
oraoci.pp(1437) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
       Compiling .\mysql\src\mysql80dyn.pp
Start compiling package pasjpeg for target i386-win32.

**Comment by LongDirtyAnimAlf** [comment]
https://www.mail-archive.com/fpc-devel@lists.freepascal.org/msg40904.html
And search the Lazarus forum for "common.dll".
