### ISSUE TITLE
Install FPC+Laz on Linux x86_64 fails at compiling package utils-h2pas

### ISSUE THREAD

**Issue by Botster** [newpascal/fpcupdeluxe#58]
Here's the last part of the log:

`[snip]
[ 50%] Compiled package utils-fprcp                                                                          
Start compiling package utils-h2pas for target x86_64-linux.                                                 
Executing command "/usr/bin/pyacc h2pas/h2pas.y h2pas/h2pas.pas"                                             
The installer encountered the following error:                                                               
External command "/usr/bin/pyacc h2pas/h2pas.y h2pas/h2pas.pas" failed with exit code 256. Console output:   
TP Yacc Version 4.1a [April 2000], Copyright (c) 1990-2000 Albert Graef                                      
                                                                                                             
FATAL: cannot open file /usr/lib/fpc/lexyacc/yyparse.cod                                                     
                                                                                                             
Makefile:2426: recipe for target 'all' failed                                                                
Makefile:2696: recipe for target 'utils_all' failed                                                          
make[1]: *** [utils_all] Error 2                                                                             
Makefile:2940: recipe for target 'build-stamp.x86_64-linux' failed                                           
make: *** [build-stamp.x86_64-linux] Error 2                                                                 
                                                                                                             
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running make failed with exit code 512`

(BTW, the red on blue is very hard to read.)

Distro is openSUSE Leap 42.3.

`locate yyparse.cod` yields:
/usr/share/fpcsrc/3.0.4/utils/h2pas/yyparse.cod
/usr/share/fpcsrc/3.0.4/utils/tply/yyparse.cod

P.S. fpcupdeluxe looks quite interesting.

**Comment by edwinyzh** [comment]
This approach may or may not help, but it helped me to fixed strange errors:
Make a 4GB swap for your linux.

**Comment by Botster** [comment]
Thank you for your response.

But, it seems obvious to me that this is not a memory issue but a path issue:
"FATAL: cannot open file /usr/lib/fpc/lexyacc/yyparse.cod"

That file is not located in "/usr/lib/fpc/lexyacc/" on my system. It is in "/usr/share/fpcsrc/3.0.4/utils/h2pas/".

Besides, swap size should be determined by the amount of RAM and the purpose of the machine, eg. server vs. desktop. There is not a one-size-fits-all size. And, I already have a 4GB swap partition.

**Comment by LongDirtyAnimAlf** [comment]
Is this issue still there, or can this be closed ?

**Comment by Botster** [comment]
A month has gone by, and you haven't actually addressed this issue. Yet, you ask if it can be closed?? Amazing.

Do whatever you want with it.

**Comment by LongDirtyAnimAlf** [comment]
There can be many reasons, among them illness, for a delayed answer.
