### ISSUE TITLE
Forced access to ftp://ftp.freepascal.org/pub/fpc/dist/3.0.4/bootstrap

### ISSUE THREAD

**Issue by GilDianaJones** [newpascal/fpcupdeluxe#59]
Hi,

I can't access to ftp://ftp.freepascal.org/pub/fpc/dist/3.0.4/bootstrap from my place so I get the bootstrap file I put in fpcupdeluxe/fpcbootstrap/(renamed)ppcx64. When I use fpcupdeluxe to install a trunk version of FPC and Lazarus, it loads correctly the ppcx64 file but after that it try to access to the ftp.

Is it possible to don't force the access to the ftp if fpcupdeluxe find the bootstrap on the computer ?

Thanks.

**Comment by synopse** [comment]
... or even better provide a fallback with plain https download from 
github/newpascal ...

**Comment by LongDirtyAnimAlf** [comment]
The manual copying of a bootstrapper should work, if the bootstrapper has the correct name and version !
Would you mind showing me the screen-dump when this happens ?

**Comment by synopse** [comment]
when I checked the fpcupdeluxe code in installerFpc.pas, it seemed that the ftp list is always retrieved, even if there is a local bootstrap file - perhaps ftp errors may just not break excecution flow
- and, if possible, provide a https alternative: blocking FTP is made by some company policy, and also by some Internet providers (e.g. Orange over fiber in France, as reported by Gilles)

**Comment by synopse** [comment]
the message was:

> fpcupdeluxe: WARNING: FPCNativeInstaller (CheckAndGetTools): Could not get compiler list from ftp://ftp.freepascal.org/pub/fpc/dist/3.0.4/bootstrap/. Trying again

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback. Will look into it again.

**Comment by LongDirtyAnimAlf** [comment]
Release 1.6.0o gives an option to only use fpcupdeluxe bootstrappers and, if enabled, skips ftp !
