### ISSUE TITLE
x86_64 is not valid target for android

### ISSUE THREAD

**Issue by serbod** [newpascal/fpcupdeluxe#62]
When trying to install android-x86_64 crosscompiler, got message "No valid CPU target for android". Version 1.6.1b

**Comment by LongDirtyAnimAlf** [comment]
That is right ! At the moment this feature is not available.
I will add it into a new (upcoming) release !

**Comment by LongDirtyAnimAlf** [comment]
Feature is added into source.
But please note that FPC does not yet support target x86_64 for Android !!
Also Aarch64 is not yet supported !
