### ISSUE TITLE
Fpcupdeluxe cant' download and install svn because of bad download url

### ISSUE THREAD

**Issue by MaxTerentiev** [newpascal/fpcupdeluxe#63]
If svn not installed Fpcupdeluxe try to download and install it. But they fail because wrong download
link used:

https://sourceforge.net/projects/win32svn/files/1.8.15/apache24/svn-win32-1.8.17-ap24.zip/download

So, they try to download 1.8.17 version from 1.8.15 folder ! And fails of course.

**Comment by LongDirtyAnimAlf** [comment]
Confirmed !
Will be solved in next release. Thanks.
