### ISSUE TITLE
fpcupdeluxe-x86_64-darwin-qt5 closes on MacOS 10.13.6

### ISSUE THREAD

**Issue by Tj85710** [newpascal/fpcupdeluxe#64]
Hello,
I am trying to install a Qt version of Lazarus 64bits. I have no problem with fpcupdeluxe-x86_64-darwin-cocoa, but on the same (virtual) machine the Qt version does not start. In fact, it dies immediately, without any message. Does it expect some prerequisites ?

Thierry

**Comment by LongDirtyAnimAlf** [comment]
Confirmed !
However, I do not have time to look into this issue right now.

Please use 1.6.0t, which is the latest working version for QT5 on Mac ... :-(

https://github.com/newpascal/fpcupdeluxe/releases/tag/v1.6.0t

**Comment by LongDirtyAnimAlf** [comment]
Latest release should work again !

https://github.com/newpascal/fpcupdeluxe/releases/tag/v1.6.1h

https://github.com/newpascal/fpcupdeluxe/releases/download/v1.6.1h/fpcupdeluxe-x86_64-darwin-qt5.app.zip
