### ISSUE TITLE
Installing behind a proxy fails.

### ISSUE THREAD

**Issue by mariovaldez** [newpascal/fpcupdeluxe#66]
After setting the options "HTTP proxy URL" and "HTTP proxy port", the message "Got an unexpected exception ... don't know what to do unfortunately" appears, the last lines in the "log console" are:

fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at: failure
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision: 37149
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No FPC patches defined.
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: info: FPC builder: Detected source version FPC: 3.0.4
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): To compile this FPC, we need (required) a compiler with version 3.0.0 or 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for a bootstrap compiler from official FPC bootstrap binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.0.0
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 2.6.4
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 2.6.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Got a bootstrap compiler from official FPC bootstrap sources.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Now looking for a better [version] bootstrap compiler from Github FPCUP(deluxe) releases. 

In the log of our network firewall appears some connections attemps to the IP 192.30.253.116, port 443; so those are HTTPS connections to GitHub. 

Is it because of the lack of HTTPS proxy support in TFPHTTPClient? Reading the code from fpcuputil.pas I see it uses fphttpclient. And reading the fphttpclient.pp file it seems there is no code to do the HTTP tunneling used by HTTPS clients behind a proxy (using the HTTP CONNECT method to let the proxy pass the encrypted data to the remote server).

So I guess there is no fix for this, unless the fphttpclient component is updated to implement that.

**Comment by LongDirtyAnimAlf** [comment]
You are right: no fix for this unfortunately !

However, you should be able to solve this by doing some work yourself.

Just download the right bootstrap compiler yourself from here:
https://github.com/newpascal/fpcupdeluxe/releases/tag/bootstrappers_v1.0

However, there are more uses of fphttpclient inside of fpcupdeluxe .... and these will likely also fail ... :-(

Good luck.

**Comment by LongDirtyAnimAlf** [comment]
Mmmmm ... I was wrong ...
FPC trunk has proxy support !

I have improved proxy support in fpcupdeluxe.
Will be included in next release.

**Comment by LongDirtyAnimAlf** [comment]
Please test the newest release.

https://github.com/newpascal/fpcupdeluxe/releases/tag/v1.6.1h
