### ISSUE TITLE
Lazarus IDE sees my code changes but fpc dont.

### ISSUE THREAD

**Issue by cpicanco** [newpascal/fpcupdeluxe#68]
I have reported this issue here: http://forum.lazarus.freepascal.org/index.php/topic,42620.0.html

Basically, after installing lazarus+fpc stable and some cross-compilers using fpcupdeluxe, I changed some code inside fpcsrc (from the libvlc package) and now I am not able to compile this code using the lazarus-ide. Can you give some light here? What should I do so that fpc will see my fpcsrc changes?

**Comment by mdbs99** [comment]
@cpicanco you need to recompile FPC than, Lazarus.
