### ISSUE TITLE
Final messages when it finished

### ISSUE THREAD

**Issue by mdbs99** [newpascal/fpcupdeluxe#69]
When fpcupdeluxe ends, remains two contradicted messages, as we can see below.
Adding just a "Done" in the message box might be enough.

BTW, amazing work.

![screenshot](https://user-images.githubusercontent.com/1459306/46245915-94ae5d80-c3cc-11e8-9617-e5b928f4cfa0.png)

**Comment by LongDirtyAnimAlf** [comment]
Done !
