### ISSUE TITLE
Don't work on MacOS Sierra

### ISSUE THREAD

**Issue by pst2d** [newpascal/fpcupdeluxe#7]
When run, I get message: Unable to create file "/private/var/folders/2s/......./AppTranslocation/440..GUID.../d/fpcupdeluxe.ini

OK to ignore and risk ...

**Comment by LongDirtyAnimAlf** [comment]
At the start of fpxupdeluxe, it tries to create the ini-files. It seems to go wrong on Sierra. Will look into it.

**Comment by LongDirtyAnimAlf** [comment]
Please have a look at this:
https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/

**Comment by pst2d** [comment]
Thanks this help me to run (move to Applications folder). Next problem is Could not find SVN executable. But this will be something with XCode.
