### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by FireInstall** [newpascal/fpcupdeluxe#70]
Maybe I'am wrong and you really lost your fixes, in this case I'm sorry, but it might supposed to be  `lots` in your [newest releas 1.6.1p](https://github.com/newpascal/fpcupdeluxe/releases/tag/1.6.1p)

> Lost of changes and bugfixes for Darwin.

**Comment by LongDirtyAnimAlf** [comment]
:-)
Lets hope that the fixes are not lost but working !
