### ISSUE TITLE
OS-Target MS-DOS can't select i386 architecture. 

### ISSUE THREAD

**Issue by turric4n** [newpascal/fpcupdeluxe#74]
Hi,

MS-DOS has two CPU architectures (i386 and i8086) but FPCUpdate only can select i8086. Can correct to use i386 too? 

Thanks!

**Comment by LongDirtyAnimAlf** [comment]
MS-DOS can only handle i8086.
See: fpmkunit.pp in .\packages\fpmkunit\src
GO32V2 has i386 as (single) target !
