### ISSUE TITLE
Slight GUI problem 

### ISSUE THREAD

**Issue by zbyna** [newpascal/fpcupdeluxe#8]
Please see video: 

[![](https://img.youtube.com/vi/Lu2qVjy6Jk0/0.jpg)](http://www.youtube.com/watch?v=Lu2qVjy6Jk0 "Click to play on Youtube.com")

**Comment by LongDirtyAnimAlf** [comment]
I have uploaded new executables with same versions, but changed GUI.
Please download again and try ?!

**Comment by zbyna** [comment]
Thanks, it is fixed now. There is another small issue with ```Halt``` button, which I did not spotted lastly :
[![](https://img.youtube.com/vi/ycsoYqgM2is/0.jpg)](http://www.youtube.com/watch?v=ycsoYqgM2is "Click to play on Youtube.com")

**Comment by LongDirtyAnimAlf** [comment]
New version. Please check again.

**Comment by zbyna** [comment]
It is OK. 👍 
Thanks.
